### ISSUE TITLE
rtai-4.1 unable to import rtai_lxrt module in python-3

### ISSUE THREAD

**Issue by mrudulachougule** [ShabbyX/RTAI#27] opened 2015-11-18 14:25 UTC
Thank you for having look at my queries. Appreciate!!
Here is little bit explanation for queries:
1) You mean to say rtai_lxrt and rtai_sched are now same in rtai-4.1 version?
2) In rtai-4.1 case rtai_lxrt.ko is soft linke of rtai_sched.ko (rtai_lxrt.ko -> rtai_sched.ko) which is not the case in rtai-3.8 any reason?
3) Since rtai_sched is getting inserted by default, when i try to insert rtai_lxrt is not allowing to insert. it says file already exists. any idea why?
4) How to import rtai_lxrt.so in python? Since I have inserted rtai_sched and not rtai_lxrt. I am not able to link with python code when running my application with python-3.
5) I am porting my code from python-2 to python-3 any idea on python-3 and rtai-4.1 how to bind so i can resolve dependencies? I am able to run my application code with python-2. Since i want to have to python-3. as python-2 support will be getting dropped soon. Please share you have any idea on changes needs to be done for rtai-4.1 to work with python-3.
6) CONFIG_RTAI_LXRT_USE_LINUX_SYSCALL option is not available to configure in rtai-4.1 where in same option is available in rtai-3.8 code. This option allows syscall to work with rtai calls when rtai is running in user space.
7)Yes. Both rtai_lxrt.ko and rtai_sched.ko are the same. Both are scheduler. But there is difference: rtai_lxrt is user space scheduler module where as rtai_sched is kernel space scheduler. They do differ in their execution respective properties.
I having my application for rtai-3.8, python-2 working well on Ubuntu-10.04. I am porting my application for rtai-4.1, python-3 on Ubunut-14.04 and not able to run it as there are some changes observed in rtai-4.1 source code where in i am not able to insert the rtai_lxrt module and when trying to insert explicitly, it's always insert rtai_sched. Any idea on modifications required for rtai-4.1 and python-3 which will work or help to resolve dependency Errors.

Please share your views. I'm Stuck!!

**Comment by ShabbyX** [comment] 2015-11-21 14:27
Duplicate of #26

**Closed** 2015-11-21 14:27 UTC
